### ISSUE TITLE
Plugin is connected to websocket server successfully but cannot receive data

### ISSUE THREAD

**Issue by tungshido** [golioth/grafana-websocket-plugin#17]
My grafana server is connected with my websocket API successfully (checked with logs file). However, when I try to send a string JSON, the plugin cannot receive and show the data. I tested my server with other clients which are all succeed to receive the JSON string. Is there any thing I need to consider when send JSON to websocket plugin?

Programming Language: Python (websockets v10)
Grafana: v8.4.4

**Comment by miguel91it** [comment]
@tungshido could you give more details of our problem?

* A sample/example of the exact string JSON that you are sending through your websocket API?

**Comment by tungshido** [comment]
> @tungshido could you give more details of your problem?
> 
> * A sample/example of the exact string JSON that you are sending through your websocket API?

Hi, this is my sample code to try stream data. I would like to send simple Json like this {"result":18}

**Server**
```
async def hello(websocket):
    name = await websocket.recv()
    await websocket.send(name)

async def main():
    async with websockets.serve(hello, "localhost", 8765):
        await asyncio.Future()  # run forever

if __name__ == "__main__":
    asyncio.run(main())
````

**Client**

```
async def hello():
    uri = "ws://localhost:8765/v1/ws/data/"
    async with websockets.connect(uri) as websocket:
        await websocket.send(json.dumps({"result":18}))
        greeting = await websocket.recv()
        print(f"<<< {greeting}")

if __name__ == "__main__":
    asyncio.run(hello())
```

Grafana logs

```
logger=plugin.golioth-websocket-datasource t=2022-03-31T21:36:27.03+0700 lvl=info msg="RunStream called" Path=.
logger=plugin.golioth-websocket-datasource t=2022-03-31T21:36:27.03+0700 lvl=info msg="Ws Connect" connectingto=ws://localhost:8765/v1/ws/data
logger=plugin.golioth-websocket-datasource t=2022-03-31T21:36:27.03+0700 lvl=info msg="Ws Connect" connectedto=ws://localhost:8765/v1/ws/data
```

**Comment by andrewsiah** [comment]
@tungshido Do you mind explaining what you did to make it work? I'm facing this same issue where I do not know how to send a payload (json.dumps) in this plugin as well. Thanks!
