### ISSUE TITLE
Combine multiple websocket sources in one panel ("mixed" data source)

### ISSUE THREAD

**Issue by m0w1337** [golioth/grafana-websocket-plugin#28]
Hello,

I'd like to combine the data from two websocket sources into one Panel, sadly the plugin does not work in combination with the "mixed" data source mode of Grafana, is there any chance to get that working, maybe?

P.S.: Thanks for this extremely helpful plugin!

**Comment by chireia** [comment]
Hey @m0w1337, unfortunately this is not possible right now given the Grafana Live API limitation, that transforms every block of new WS messages into panel data points.

We're still waiting on future enhancements for this API, but, right now, this is now an option.
